Feature/gh92 create hdmicec module
rdkcentral/python_raft pull request #105
Opened 2024-10-02 09:41 UTC by TB-1993

Created hdmiceccontroller, with. a cec-client type and integrated them with the device manager.

closes #92

2024-10-02 16:42 UTC, TB-1993 commented
@Ulrond and @zghp does the naming for this module make sense to you guys? Or do we think it would just be better has HDMIController or CECController?

2024-10-03 09:53 UTC, Ulrond commented on framework/core/hdmicecModules/cecClient.py
> +sys.path.append('/mnt/1TB/home/toby/Documents/Scripts/python/python_raft/')
need to remove that.

2024-10-03 10:18 UTC, Ulrond requested changes
- libcec client not installed, assume that's required somehow maybe in the requirements.txt
- need documentation added .

2024-10-03 10:18 UTC, Ulrond commented on framework/core/hdmicecModules/__init__.py
> +from .cecClient import CECClientController
how is this installed? is it in the reuqirements.txt?

2024-10-03 10:21 UTC, Ulrond commented on framework/core/hdmicecModules/cecClient.py
> +#*   ** @brief : cecClient controller. Class for running cec-client commands on
you'll need to update NOTICE to state that your using  a 3rd party tool and give them credit for it.
and you'll need to include URL links in this description to state that your wrapping..

2024-10-07 12:23 UTC, Ulrond commented on framework/core/hdmicecModules/__init__.py
> +from .cecClient import CECClientController
you should upgrade -> https://github.com/rdkcentral/ut-raft/blob/main/examples/host/install.sh with the template on how it should be installed.

Maybe add it as a comment rather than having it was a fully enabled thing, like unhash this to enable hdmicec plugin sort of thing.

2024-10-08 10:17 UTC, TB-1993 commented on framework/core/hdmicecModules/cecClient.py
> +sys.path.append('/mnt/1TB/home/toby/Documents/Scripts/python/python_raft/')
This should be gone now.

2024-10-08 10:19 UTC, TB-1993 commented on framework/core/hdmicecModules/cecClient.py
> +#*   ** @brief : cecClient controller. Class for running cec-client commands on
I haven't updated this, since libcec is GPL and I thought adding that to the NOTICE file would scare people more. Even though it is GPL, we don't share the source, link or compile with it so we're no obligated by any of the obligations in the licence.

2024-10-10 10:03 UTC, Ulrond reviewed
minor comments.

2024-10-10 10:03 UTC, Ulrond commented on README.md
> +#### Optional Packages
why is it optional, isn't it required?

2024-10-10 10:03 UTC, Ulrond commented on examples/configs/example_rack_config.yml
> +                    #hdmiCECController: Specific hdmiCECController for the slot
probally should be on.

At the top of the file, we should state that this is every configuration / section turned on, and based on your requirements you need to disable sections as required, sort of thing?

2024-11-01 11:20 UTC, Ulrond approved these changes
minor comment, which I don't understand what your deprecating?

2024-11-01 11:20 UTC, Ulrond commented on examples/configs/example_rack_config.yml
> +# Deprecated
if you need to talk about deprecating something, I would put it in you release notes, not your examples on how stuff works.

2024-11-01 15:25 UTC, closed without merging