Update #103: Creation of remote hdmicec client
rdkcentral/python_raft pull request #115
Opened 2024-11-07 16:40 UTC by TB-1993

Created new remote-cec-client hdmi cec controller.
Also added a threaded logging function to allow the logModule to write a continuous log stream out to a file.

closes #107

2024-11-08 11:55 UTC, Ulrond requested changes
you mentioned that your using the cecClient on a pi, where's that?

I don't see any mentioned of that or how it's used, and what it's got todo with a PI.? Isn't it just a client of cecClient, and you can do that on a PI or something else that has HDMI in.

2024-11-08 11:55 UTC, Ulrond commented on framework/core/logModule.py
> +from threading import Thread
is there no changes to requriements.txt?

2024-11-08 11:55 UTC, Ulrond commented on framework/core/logModule.py
> +    def logStreamToFile(self, inputStream: IOBase, outFileName: str) -> None:
huh?

There's no change to logging to support this.

Launch the logger with file enabled.

loggign shouldn't change just because your doing a thread.

2024-11-08 11:55 UTC, Ulrond commented on framework/core/logModule.py
> +    def logStreamToFile(self, inputStream: IOBase, outFileName: str) -> None:
I think this is outside of the scope for logModule.

This is an stream input class, that can write to files., I can't see it being related to `logModule()`

it uses logModule for writing data to logs, nothing todo with the module though, it's a user of logModule()

2024-11-08 11:55 UTC, Ulrond commented on framework/core/hdmicecModules/remoteCECClient.py
> +            deviceType (MonitoringType, optional): The type of device to monitor (default: MonitoringType.RECORDER).
it's outside of scope of the user of the API to know anything about what's under it, and what type of device you need to control , or how it's monitored.

2024-11-08 11:57 UTC, Ulrond commented on framework/core/hdmicecModules/remoteCECClient.py
> +    def startMonitoring(self, monitoringLog: str, deviceType: MonitoringType=MonitoringType.RECORDER) -> None:
don't see any caller to this module? Where is it linked to anything about it?

2024-11-08 16:48 UTC, TB-1993 commented on framework/core/logModule.py
> +from threading import Thread
threading is standard library, so we're all good here.

2024-11-08 16:49 UTC, TB-1993 commented on framework/core/hdmicecModules/remoteCECClient.py
> +    def startMonitoring(self, monitoringLog: str, deviceType: MonitoringType=MonitoringType.RECORDER) -> None:
No you can't monitor and send messages from the same module, monitoring is blocking. So you'd need to decide what you want to do with the device in the test.

2024-12-18 19:07 UTC, TB-1993 commented
The new versions of these still have issues, the remoteCECClient isn't consistent due to the implementation of the readUntil in the sshConsole. I'll raise a bug ticket to get this fixed.

2024-12-19 14:59 UTC, TB-1993 commented on framework/core/hdmicecModules/remoteCECClient.py
> +        self._console.write(f'echo "scan" | cec-client -s {self.adaptor} -d 1 > cec-test.txt')
Writing it to a file is definitely wrong

2024-12-23 12:55 UTC, bhanucbp approved these changes
ship it

2024-12-23 12:58 UTC, merged