gh70 - integrate decodeParams with singleton
rdkcentral/python_raft pull request #76
Opened 2024-07-09 14:41 UTC by zghp

<img width="1244" alt="Screenshot 2024-07-09 at 15 38 26" src="https://github.com/rdkcentral/python_raft/assets/33546213/f3196c3e-437c-4be8-a1d4-d33dc19d8e1c">

2024-07-09 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/python_raft?pullRequest=76) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/python_raft?pullRequest=76) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Ulrond<br/>:x: zghp<br/><hr/>**zghp** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/python_raft?pullRequest=76) it.</sub>

2024-07-10 14:01 UTC, TB-1993 requested changes
Don't forget to clean up all the commented out code too

2024-07-10 14:01 UTC, TB-1993 commented on tests/test_decodeParams.py
> +    unittest.main(argv=[sys.argv[0]] + remaining_args, exit=False)
Shouldn't need to manipulate argv for main to run. We need that to be handled in the singleton or in a RAFTTestMain function.

2024-07-11 10:09 UTC, zghp commented on framework/core/decodeParams.py
> +        deviceConfigFile = self.args.configFile
tried running exceptionTests.py w/ self.args.deviceConfigFile => no config file 
(but works with self.args.configFile)

2024-07-11 10:10 UTC, zghp commented on framework/core/singleton.py
> +singleton = Singleton(log=None)
done

2024-07-11 10:26 UTC, zghp commented on tests/test_decodeParams.py
> +        # Load and process the config file if needed
done

2024-07-15 15:31 UTC, TB-1993 requested changes

2024-07-15 15:31 UTC, TB-1993 commented on framework/core/raftUnittest.py
> +        unittest.main(argv=[sys.argv[0]] + remaining_args, exit=False)
Wasn't expecting this function to exist at all.
All argument parsing must be done in decodeParams as part of the Singleton.

2024-07-15 15:31 UTC, TB-1993 commented on framework/core/raftUnittest.py
> +        self.deviceManager = SINGLETON.deviceManager
Didn't we decide we didn't need this.

At mosts we'd want:
```python
def RAFTmain():
    if SINGLETON.loop:
        for i in SINGLETON.loop:
            unittest.main()
```
But I'd hope there was a better way to do that.

2024-07-15 15:31 UTC, TB-1993 commented on tests/test_decodeParams.py
> +            print("No loop provided")
Make this a proper unittest test using asserts. e.g.
```python
def test_decodeParams(self):
    self.assertEqual(SINGLETON.params.args.slot, 1, 'Test the slot value is 1')
```
So the test will pass when I run it with `--slot 1` but fail when I run it with `--slot 2`.

2024-07-16 08:53 UTC, Ulrond commented on framework/core/raftUnittest.py
> +class RAFTUnitTestMain(unittest.TestCase):
don't see a test for the testSuite, only a testcase.

2024-07-18 15:01 UTC, TB-1993 commented on tests/test_decodeParams.py
> +            self.fail("No rack name provided")
Doesn't the assert fail anyway if params.rackName isn't set?

2024-07-18 15:02 UTC, TB-1993 commented on tests/test_decodeParams.py
> +        $ python tests/test_decodeParams.py --config examples/configs/getting_started_rack_config.yml --rack rack2 --slotName slot3 --loop 1
Can we do a run with every possible switch and then check all of them in this test?

2024-07-19 11:12 UTC, TB-1993 approved these changes

2024-07-19 11:13 UTC, TB-1993 commented
Ship it!

2024-07-19 11:23 UTC, merged