Feature/gh75 documentation for unittest raft
rdkcentral/python_raft pull request #87
Opened 2024-08-09 14:59 UTC by TB-1993

Added documented example test for new unittest style of writing tests.
Fixed a bug in SSHConsole using port incorrectly.

closes #75

2024-08-09 14:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/python_raft?pullRequest=87) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/python_raft?pullRequest=87) before we can accept your contribution.<br/><hr/>**Toby Baldock** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/python_raft?pullRequest=87) it.</sub>

2024-08-09 15:08 UTC, Ulrond requested changes
session seems weird. Where's the code commit review for the new framework?

2024-08-09 15:08 UTC, Ulrond commented on examples/code/example_ssh_unittest.py
> +        self.session = self.dut.getConsoleSession()
self.session should already exist surely, the framework should have done that?
self.power
self.device
self.log
etc..
should all be setup.

2024-08-09 15:08 UTC, Ulrond commented on examples/code/example_ssh_unittest.py
> +        self.log.stepStart(f'Creating {TEST_FILE} in {TEST_DIRECTORY}')
do we still need stepStart, isn't that handled in the framework?

2024-08-29 11:34 UTC, zghp requested changes

2024-08-29 11:34 UTC, zghp commented on examples/code/example_ssh_unittest.py
> +        self.dut.session.write(f'ls {TEST_DIRECTORY}')
self.dut.session.write(f'ls {TEST_DIRECTORY}')
        file_list = self.dut.session.read_all()

the code is repeated twice in both methods so maybe can organise this bit into a helper method (e.g. list_files())

2024-08-30 11:06 UTC, Ulrond commented on examples/code/example_ssh_unittest.py
> +        file_list = utilities.strip_ansi_escapes(self.dut.session.read_all())
These are bad examples, and I had to fix the usage of it for the other teams.

we need to ensure we wait for a prompt when we run commands in all cases for all things.

The waitForSessionMessagePromp() needs to return the text of what was waited for, and it needs to wait for a prompt.

2024-08-30 11:06 UTC, Ulrond commented on examples/code/example_ssh_unittest.py
> +        file_list = utilities.strip_ansi_escapes(self.dut.session.read_all())
`session.read_all()` must never be used in any of our examples.

2024-08-30 11:10 UTC, Ulrond commented on examples/code/example_ssh_unittest.py
> +        file_list = utilities.strip_ansi_escapes(self.dut.session.read_all())
or this -> `writeCommandOnDevice(self, command, prompt=None, device="dut"):` -> https://github.com/rdkcentral/ut-raft/pull/4/files#diff-f4c4730e180ac270dfa2f6cd02717b1ae94a0d105c2e09bcde08eebbd5b3c89dR270

2024-09-20 11:47 UTC, merged